import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <h1>My Next.js App</h1>
        </header>
        {children}
        <footer
          style={{ backgroundColor: "purple", color: "white", padding: "1rem" }}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
